#!/usr/bin/env bash

set -e

run() {
    printf >&2 " > "
    printf >&2 "%q " "$@"
    printf >&2 "\n"
    "$@"
    return $?
}

# show what is happening
echo >&2 "if-up    : $0"
echo >&2 "CONFBASE : $CONFBASE"
echo >&2 "IFNAME   : $IFNAME"
echo >&2 "IFTYPE   : $IFTYPE"
echo >&2 "IFSUBTYPE: $IFSUBTYPE"
echo >&2 "IFUPDATA : $IFUPDATA"
echo >&2 "NODEID   : $NODEID"
echo >&2 "NODENAME : $NODENAME"
echo >&2 "MAC      : $MAC"
echo >&2 "MTU      : $MTU"
echo >&2 "NODES    : $NODES"

# parse the IP and NET from $IFUPDATA
NET="$(echo "$IFUPDATA" | cut -d '|' -f 1)"
IP="$(echo "$IFUPDATA" | cut -d '|' -f 2)"
echo >&2 "IP       : $IP"
echo >&2 "NET      : $NET"

# bring it up
run ip link set $IFNAME address $MAC mtu $MTU up
run ip addr add $IP dev $IFNAME
run ip route replace $NET dev $IFNAME || run ip route add $NET dev $IFNAME

cat >$CONFBASE/status/$NODEID <<EOF
nodeid=$NODEID
name=$NODENAME
status=up
ip=$IP
si=
rip=
ripport=
timestamp=$(date +%s)
EOF

exit 0
